# Generated by Django 3.2.6 on 2021-08-10 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('datainicio', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 13, 31, 45, 966748, tzinfo=utc))),
                ('mostrar', models.BooleanField(default=True)),
            ],
        ),
    ]
